# Generated by Django 6.0.7 on 2026-07-21 06:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('inspection_type', models.CharField(max_length=20)),
                ('shift', models.CharField(choices=[('A', 'Shift A'), ('B', 'Shift B'), ('C', 'Shift C')], default='A', max_length=1)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='in_progress', max_length=20)),
                ('total_parameters', models.PositiveIntegerField(default=0)),
                ('recorded_count', models.PositiveIntegerField(default=0)),
                ('has_ooc', models.BooleanField(default=False)),
                ('has_critical_fail', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_remark', models.TextField(blank=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='machines.machine')),
            ],
            options={
                'db_table': 'inspection_sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
