# Generated by Django 6.0.7 on 2026-07-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionsession',
            name='last_measurement_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionsession',
            name='operator_reminded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionsession',
            name='operator_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionsession',
            name='supervisor_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionsession',
            name='supervisor_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
