# Generated by Django 6.0.7 on 2026-07-24 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_inspectionsession_last_measurement_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionsession',
            name='parent_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_trials', to='inspections.inspectionsession'),
        ),
        migrations.AddField(
            model_name='inspectionsession',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspectionsession',
            name='trial_number',
            field=models.IntegerField(default=1),
        ),
    ]
