# Generated by Django 6.0.7 on 2026-07-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_inspectionsession_parent_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionsession',
            name='hourly_unlocked_slot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inspectionsession',
            name='is_setup_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionsession',
            name='shift_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionsession',
            name='supervisor_override_active',
            field=models.BooleanField(default=False),
        ),
    ]
