# Generated by Django 6.0.7 on 2026-07-28 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_inspectionsession_hourly_unlocked_slot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionsession',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionsession',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionsession',
            name='is_first_piece_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionsession',
            name='pdf_report_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('finalized_passed', 'Finalized (Passed)'), ('finalized_failed', 'Finalized (Failed)'), ('completed', 'Completed')], default='in_progress', max_length=25),
        ),
    ]
