# Generated by Django 6.0.7 on 2026-08-12 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_inspectionsession_finalized_at_and_more'),
        ('machines', '0001_initial'),
        ('parts', '0008_processparameter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('operation', models.CharField(blank=True, default='', max_length=100)),
                ('shift', models.CharField(choices=[('A', 'Shift A'), ('B', 'Shift B'), ('C', 'Shift C')], default='A', max_length=1)),
                ('production_target', models.PositiveIntegerField(default=0)),
                ('jobs_completed', models.PositiveIntegerField(default=0)),
                ('correct_jobs', models.PositiveIntegerField(default=0)),
                ('incorrect_jobs', models.PositiveIntegerField(default=0)),
                ('cr_count', models.PositiveIntegerField(default=0)),
                ('mr_count', models.PositiveIntegerField(default=0)),
                ('rw_count', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True, default='')),
                ('achievement_percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_reports', to='machines.machine')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_reports', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_reports', to='parts.part')),
            ],
            options={
                'db_table': 'daily_production_reports',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
