# Generated by Django 6.0.7 on 2026-08-22 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_dailyproductionreport'),
        ('parts', '0009_processparameter_measurement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionsession',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='parts.inspectiontemplate'),
        ),
    ]
