# Generated by Django 6.0.7 on 2026-08-29 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_add_template_fk_to_inspection_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproductionreport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='SUBMITTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyproductionreport',
            name='shift',
            field=models.CharField(default='A', max_length=20),
        ),
        migrations.CreateModel(
            name='DowntimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('no_load', models.PositiveIntegerField(default=0)),
                ('no_operator', models.PositiveIntegerField(default=0)),
                ('um', models.PositiveIntegerField(default=0)),
                ('setting', models.PositiveIntegerField(default=0)),
                ('inspection_wait', models.PositiveIntegerField(default=0)),
                ('tool_change', models.PositiveIntegerField(default=0)),
                ('power_off', models.PositiveIntegerField(default=0)),
                ('rework', models.PositiveIntegerField(default=0)),
                ('tool_problem', models.PositiveIntegerField(default=0)),
                ('total_downtime', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_downtime_reports', to=settings.AUTH_USER_MODEL)),
                ('production_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='downtime_report', to='inspections.dailyproductionreport')),
            ],
            options={
                'db_table': 'downtime_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
