# Generated by Django 5.1.5 on 2026-09-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_dailyproductionreport_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtimereport',
            name='expected_downtime',
            field=models.PositiveIntegerField(default=0, help_text='Mathematically expected downtime'),
        ),
    ]
