# Generated by Django 6.0.7 on 2026-09-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0010_downtimereport_expected_downtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproductionreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='dailyproductionreport',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dailyproductionreport',
            name='shift',
            field=models.CharField(db_index=True, default='A', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyproductionreport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], db_index=True, default='SUBMITTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='downtimereport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='downtimereport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspectionsession',
            name='inspection_type',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspectionsession',
            name='shift',
            field=models.CharField(choices=[('A', 'Shift A'), ('B', 'Shift B'), ('C', 'Shift C')], db_index=True, default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='inspectionsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='inspectionsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('finalized_passed', 'Finalized (Passed)'), ('finalized_failed', 'Finalized (Failed)'), ('completed', 'Completed')], db_index=True, default='in_progress', max_length=25),
        ),
    ]
