# Generated by Django 6.0.7 on 2026-09-09 06:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0011_alter_dailyproductionreport_created_at_and_more'),
        ('machines', '0005_merge_20260905_1146'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JHChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_no', models.CharField(db_index=True, max_length=20)),
                ('assembly', models.CharField(db_index=True, max_length=100)),
                ('sub_assembly', models.CharField(blank=True, default='', max_length=100)),
                ('check_point', models.TextField()),
                ('standard', models.TextField()),
                ('tool_type', models.CharField(choices=[('VISUAL', 'Visual (Eye)'), ('TOUCH', 'Touch (Hand)'), ('TOOL', 'Tool / Wrench (Spanner)')], default='VISUAL', max_length=20)),
                ('rank', models.CharField(blank=True, default='D', max_length=10)),
                ('frequency', models.CharField(default='D', max_length=10)),
                ('action_clean', models.BooleanField(default=False)),
                ('action_lubricate', models.BooleanField(default=False)),
                ('action_inspect', models.BooleanField(default=True)),
                ('action_retighten', models.BooleanField(default=False)),
                ('timing_sec', models.CharField(default='5 DPT', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'jh_checklist_items',
                'ordering': ['sort_order', 'sub_no'],
            },
        ),
        migrations.CreateModel(
            name='JHInspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('shift', models.CharField(choices=[('I', 'Shift I'), ('II', 'Shift II'), ('III', 'Shift III')], db_index=True, default='I', max_length=10)),
                ('status', models.CharField(choices=[('ALL_OK', 'All OK'), ('HAS_ISSUES', 'Has Issues'), ('CORRECTED', 'Issues Corrected')], db_index=True, default='ALL_OK', max_length=20)),
                ('total_items', models.IntegerField(default=0)),
                ('ok_items', models.IntegerField(default=0)),
                ('not_ok_items', models.IntegerField(default=0)),
                ('corrected_items', models.IntegerField(default=0)),
                ('overall_remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jh_inspections', to='machines.machine')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jh_inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jh_inspection_records',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('machine', 'date', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='JHInspectionItemResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'Not OK'), ('CORRECTED', 'Not OK Correction Done')], default='OK', max_length=20)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('action_taken', models.CharField(blank=True, default='', max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_results', to='inspections.jhchecklistitem')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_results', to='inspections.jhinspectionrecord')),
            ],
            options={
                'db_table': 'jh_inspection_item_results',
                'unique_together': {('inspection', 'item')},
            },
        ),
    ]
