# Generated by Django 6.0.7 on 2026-09-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0012_jhchecklistitem_jhinspectionrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproductionreport',
            name='shift',
            field=models.CharField(db_index=True, default='I', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspectionsession',
            name='shift',
            field=models.CharField(choices=[('I', 'Shift I'), ('II', 'Shift II'), ('III', 'Shift III'), ('A', 'Shift A'), ('B', 'Shift B'), ('C', 'Shift C')], db_index=True, default='I', max_length=5),
        ),
    ]
