# Generated by Django 5.1.5 on 2026-09-10 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0013_add_document_payload_gin_index'),
        ('inspections', '0013_alter_dailyproductionreport_shift_and_more'),
    ]

    operations = [
    ]
