# Generated by Django 6.0.7 on 2026-09-09 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0013_alter_dailyproductionreport_shift_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JHChecklistVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(db_index=True, unique=True)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_items', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jh_checklist_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='jhchecklistitem',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.jhchecklistversion'),
        ),
    ]
