# Generated by Django 6.0.7 on 2026-09-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0013_add_document_payload_gin_index'),
        ('inspections', '0013_alter_dailyproductionreport_shift_and_more'),
    ]

    operations = [
    ]
