# Generated by Django 6.0.7 on 2026-09-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0013_add_document_payload_gin_index'),
        ('inspections', '0014_jhchecklistversion_jhchecklistitem_version'),
    ]

    operations = [
    ]
