# Generated by Django 6.0.7 on 2026-09-10 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0014_merge_20260910_1116'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='setupapproval',
            new_name='inspection__templat_ff8fbe_idx',
            old_name='setup_appr_templat_machine_idx',
        ),
    ]
