# Generated by Django 5.1.5 on 2026-09-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0014_merge_20260910_1000'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='setupapproval',
            new_name='inspection__templat_ff8fbe_idx',
            old_name='setup_appr_templat_machine_idx',
        ),
    ]
