# Generated by Django 6.0.7 on 2026-09-09 11:35
# Modified: Made no-op to avoid duplicate index rename conflict with 0015

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0015_merge_20260909_1657'),
    ]

    operations = [
        # No operations - the index rename is already performed by
        # 0015_rename_setup_appr_templat_machine_idx_inspection__templat_ff8fbe_idx
        # in the parallel migration branch. Making this a no-op prevents
        # "index does not exist" errors on fresh database deployments.
    ]
