# Generated by Django 6.0.7 on 2026-09-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0015_merge_20260909_1657'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='setupapproval',
            new_name='inspection__templat_ff8fbe_idx',
            old_name='setup_appr_templat_machine_idx',
        ),
    ]
