# Generated by Django 5.1.5 on 2026-09-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0015_rename_setup_appr_templat_machine_idx_inspection__templat_ff8fbe_idx'),
        ('inspections', '0016_rename_setup_appr_templat_machine_idx_inspection__templat_ff8fbe_idx'),
    ]

    operations = [
    ]
