# Generated by Django 6.0.7 on 2026-09-29 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0017_merge_20260910_1502'),
        ('machines', '0008_factory_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jhchecklistitem',
            name='machine',
            field=models.ForeignKey(blank=True, help_text='Machine this checkpoint belongs to. Null = factory default template.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jh_checklist_items', to='machines.machine'),
        ),
        migrations.AddField(
            model_name='jhchecklistversion',
            name='machine',
            field=models.ForeignKey(blank=True, help_text='Machine this checklist version belongs to. Null = factory default template.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jh_checklist_versions', to='machines.machine'),
        ),
        migrations.AlterField(
            model_name='jhchecklistversion',
            name='version_number',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name='jhchecklistversion',
            constraint=models.UniqueConstraint(fields=('machine', 'version_number'), name='unique_machine_version'),
        ),
        migrations.AddConstraint(
            model_name='jhchecklistversion',
            constraint=models.UniqueConstraint(condition=models.Q(('machine__isnull', True)), fields=('version_number',), name='unique_default_version'),
        ),
    ]
