# Generated by Django 6.0.7 on 2026-10-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0018_jhchecklistitem_machine_jhchecklistversion_machine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupapproval',
            name='shift',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
