# Generated by Django 6.0.7 on 2026-09-11 10:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_level',
            field=models.CharField(choices=[('L1', 'L1 — Quality Manual & Policies'), ('L2', 'L2 — Standard Operating Procedures (SOP)'), ('L3', 'L3 — Work Instructions & Standards'), ('L4', 'L4 — Forms, Formats & Checklists')], db_index=True, default='L2', help_text='IATF/ISO Document Hierarchy Tier', max_length=2),
        ),
        migrations.CreateModel(
            name='DocumentChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dcr_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date_of_receipt', models.DateField(default=django.utils.timezone.now)),
                ('document_description', models.TextField(help_text='What the document currently states')),
                ('basis_for_change', models.TextField(help_text='Reason / technical basis for change')),
                ('review_remark', models.TextField(blank=True, help_text='Change Review Remark')),
                ('implementation_date', models.DateField(blank=True, help_text='Change to be implemented from', null=True)),
                ('cft_remarks', models.TextField(blank=True, help_text='CFT Remarks')),
                ('calibrator_remarks', models.TextField(blank=True, help_text='Calibrator Remarks')),
                ('date_of_review', models.DateTimeField(blank=True, null=True)),
                ('mr_remarks', models.TextField(blank=True, help_text='Management Representative remarks')),
                ('date_of_approval', models.DateTimeField(blank=True, null=True)),
                ('rejection_stage', models.CharField(blank=True, max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('date_of_rejection', models.DateTimeField(blank=True, null=True)),
                ('implemented_notes', models.TextField(blank=True, help_text='Change implemented with documents')),
                ('implemented_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('awaiting_review', 'Awaiting Review'), ('reviewed', 'Reviewed'), ('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented')], db_index=True, default='submitted', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dcrs', to=settings.AUTH_USER_MODEL)),
                ('assigned_approver', models.ForeignKey(blank=True, help_text='Assigned Management Representative / Admin Approver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dcr_approvals', to=settings.AUTH_USER_MODEL)),
                ('assigned_calibrator', models.ForeignKey(blank=True, help_text='Assigned Calibrator for verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dcr_calibrator_reviews', to=settings.AUTH_USER_MODEL)),
                ('assigned_cft_reviewer', models.ForeignKey(blank=True, help_text='Assigned Cross-Functional Team Reviewer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dcr_cft_reviews', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='document_control.document')),
                ('implemented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implemented_dcrs', to=settings.AUTH_USER_MODEL)),
                ('implemented_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implemented_from_dcr', to='document_control.document')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raised_dcrs', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_dcrs', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_dcrs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Change Request',
                'verbose_name_plural': 'Document Change Requests',
                'db_table': 'document_change_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DCRNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_type', models.CharField(choices=[('review_requested', 'Review Requested'), ('approval_requested', 'Approval Requested'), ('dcr_approved', 'DCR Approved'), ('dcr_rejected', 'DCR Rejected'), ('dcr_implemented', 'DCR Implemented'), ('general', 'General')], default='general', max_length=30)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcr_notifications', to=settings.AUTH_USER_MODEL)),
                ('dcr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='document_control.documentchangerequest')),
            ],
            options={
                'verbose_name': 'DCR Notification',
                'verbose_name_plural': 'DCR Notifications',
                'db_table': 'document_dcr_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
