# Generated by Django 6.0.7 on 2026-09-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_control', '0002_document_doc_level_documentchangerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchangerequest',
            name='form_doc_no',
            field=models.CharField(blank=True, default='DKI/MR/F/05', max_length=50),
        ),
        migrations.AddField(
            model_name='documentchangerequest',
            name='issue_no_date',
            field=models.CharField(blank=True, default='01/01.04.2018', max_length=50),
        ),
        migrations.AddField(
            model_name='documentchangerequest',
            name='rev_no_date',
            field=models.CharField(blank=True, default='01/01.04.2018', max_length=50),
        ),
    ]
