# Generated by Django 5.1.5 on 2026-09-12 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_control', '0003_documentchangerequest_form_doc_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
        migrations.DeleteModel(
            name='DocumentCategory',
        ),
    ]
