# Generated by Django 6.0.7 on 2026-09-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_control', '0004_remove_document_category_delete_documentcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='revision_date',
            field=models.DateField(blank=True, help_text='Date of current revision', null=True),
        ),
    ]
