# Generated by Django 6.0.7 on 2026-09-21 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_control', '0005_document_revision_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcrnotification',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='document_control.document'),
        ),
        migrations.AlterField(
            model_name='dcrnotification',
            name='action_type',
            field=models.CharField(choices=[('review_requested', 'Review Requested'), ('approval_requested', 'Approval Requested'), ('dcr_approved', 'DCR Approved'), ('dcr_rejected', 'DCR Rejected'), ('dcr_implemented', 'DCR Implemented'), ('doc_review_requested', 'Document Review Requested'), ('doc_approval_requested', 'Document Approval Requested'), ('doc_approved', 'Document Approved'), ('doc_rejected', 'Document Rejected'), ('general', 'General')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='dcrnotification',
            name='dcr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='document_control.documentchangerequest'),
        ),
    ]
