# Generated by Django 6.0.7 on 2026-09-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_control', '0007_document_approved_at_document_reviewed_at_and_more'),
        ('users', '0010_seed_editable_common_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, related_name='controlled_documents', to='users.accessrole'),
        ),
        migrations.AlterField(
            model_name='documentactivity',
            name='action',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('submitted_review', 'Submitted for Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revised', 'New Revision Uploaded'), ('downloaded', 'Downloaded'), ('obsoleted', 'Marked Obsolete'), ('comment', 'Comment Added'), ('access_updated', 'Visibility Access Updated')], max_length=30),
        ),
    ]
