# Generated by Django 6.0.7 on 2026-09-28 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_control', '0008_document_allowed_roles_alter_documentactivity_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_preview', models.BooleanField(default=False)),
                ('can_download', models.BooleanField(default=False)),
                ('can_print', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='document_control.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document User Permission',
                'verbose_name_plural': 'Document User Permissions',
                'db_table': 'document_user_permissions',
                'ordering': ['user__first_name', 'user__last_name'],
                'unique_together': {('document', 'user')},
            },
        ),
    ]
