# Generated by Django 6.0.7 on 2026-07-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operator', 'Operator'), ('supervisor', 'Supervisor'), ('quality_engineer', 'Inspector'), ('admin', 'Admin')], default='operator', max_length=20),
        ),
    ]
