# Generated by Django 6.0.7 on 2026-09-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_verification_token_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_shift',
            field=models.CharField(choices=[('I', 'Shift I'), ('II', 'Shift II'), ('III', 'Shift III'), ('ALL', 'All Shifts (Flexible)')], default='ALL', help_text='Assigned working shift for the operator/inspector.', max_length=10),
        ),
    ]
