# Generated by Django 5.1.5 on 2026-09-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_voicelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
