# Generated by Django 5.1.5 on 2026-09-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_conversation_pinned_messages'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messagereaction',
            new_name='message_rea_message_3fb393_idx',
            old_name='message_reactions_message_idx',
        ),
    ]
