# Generated by Django 5.1.5 on 2026-09-20 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_rename_message_reactions_message_idx_message_rea_message_3fb393_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationClearHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleared_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleared_history', to='messaging.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleared_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversation_clear_history',
                'unique_together': {('user', 'conversation')},
            },
        ),
    ]
