# Generated by Django 5.1.5 on 2026-09-20 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_conversationclearhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='past_participants',
            field=models.ManyToManyField(blank=True, related_name='past_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
