from django.core.management.base import BaseCommand
from apps.inspections.models import JHChecklistItem

CHECKLIST_ITEMS = [
    # 1. Machine Front Side
    {
        "sub_no": "1.1",
        "assembly": "1. Machine Front Side",
        "sub_assembly": "एफ एम एफ बोर्ड",
        "check_point": "पूरा एफ एम एफ बोर्ड साफ करो (Clean complete FMF board)",
        "standard": "धूल और तेल से मुक्त (Free from dust and oil)",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "B",
        "frequency": "D",
        "action_clean": True,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "5 DPT",
        "sort_order": 1,
    },
    {
        "sub_no": "1.2",
        "assembly": "1. Machine Front Side",
        "sub_assembly": "एफ आर एल",
        "check_point": "एफ आर एल का एयर प्रेशर गेज में प्रेशर ग्रीन रेंज में है क्या चेक करो (Check FRL air pressure gauge is in green range)",
        "standard": "ग्रीन निशान (5-6 bar)",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "D",
        "frequency": "D",
        "action_clean": False,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "5 DPT",
        "sort_order": 2,
    },
    {
        "sub_no": "1.3",
        "assembly": "1. Machine Front Side",
        "sub_assembly": "एफ आर एल",
        "check_point": "एफ आर एल का आयल लेवल ग्रीन रेंज में है क्या चेक करो (Check FRL oil level in green range)",
        "standard": "भरा निशान (Full mark indicator)",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "D",
        "frequency": "D",
        "action_clean": False,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "5 DPT",
        "sort_order": 3,
    },
    {
        "sub_no": "1.4",
        "assembly": "1. Machine Front Side",
        "sub_assembly": "एफ आर एल",
        "check_point": "एफ आर एल का फिल्टर से ड्रेन बटन दबाकर पानी निकालो (Drain water from FRL filter button)",
        "standard": "पानी नहीं होना चाहिए (No water presence)",
        "tool_type": JHChecklistItem.ToolType.TOUCH,
        "rank": "D",
        "frequency": "D",
        "action_clean": False,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "5 DPT",
        "sort_order": 4,
    },
    {
        "sub_no": "1.5",
        "assembly": "1. Machine Front Side",
        "sub_assembly": "ए पी एस / जी पी एस",
        "check_point": "ए पी एस का एयर प्रेशर गेज & जी पी एस गैस प्रेशर चेक करो (Check APS air pressure & GPS gas pressure)",
        "standard": "4-6 bar / 0.40-2 bar",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "D",
        "frequency": "D",
        "action_clean": False,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "5 DPT",
        "sort_order": 5,
    },
    {
        "sub_no": "1.6",
        "assembly": "1. Machine Front Side",
        "sub_assembly": "तार चैनल",
        "check_point": "वायर हैंगिंग केबल ट्रे में होनी चाहिए (Check wire hanging in cable tray)",
        "standard": "तार ठीक से बंधी (Wires properly bundled & tied)",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "D",
        "frequency": "D",
        "action_clean": False,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "5 DPT",
        "sort_order": 6,
    },
    {
        "sub_no": "1.7",
        "assembly": "1. Machine Front Side",
        "sub_assembly": "गैस फ्लोमीटर",
        "check_point": "गैस फ्लोमीटर गैस प्रेशर ग्रीन रेंज में है क्या चेक करो (Check gas flowmeter in green range)",
        "standard": "गैस लीकेज न हो (10-15 L/min)",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "D",
        "frequency": "D",
        "action_clean": False,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "5 DPT",
        "sort_order": 7,
    },

    # 2. FIXTURE
    {
        "sub_no": "2.1",
        "assembly": "2. FIXTURE",
        "sub_assembly": "वेल्डर",
        "check_point": "पार्ट क्लैंपिंग सतह सफाई (Part clamping surface cleaning)",
        "standard": "स्पैटर या कचरा न हो (Free from spatter or debris)",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "D",
        "frequency": "D",
        "action_clean": True,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "60 DPT",
        "sort_order": 8,
    },
    {
        "sub_no": "2.2",
        "assembly": "2. FIXTURE",
        "sub_assembly": "वेल्डर",
        "check_point": "पार्ट क्लीयरेंस गैप चेक करो (Check part clearance gap)",
        "standard": "गैप सही है कोई अनचाहा गैप नहीं (Uniform clearance)",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "D",
        "frequency": "D",
        "action_clean": False,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "60 DPT",
        "sort_order": 9,
    },
    {
        "sub_no": "2.3",
        "assembly": "2. FIXTURE",
        "sub_assembly": "फिक्सचर",
        "check_point": "लोकेशन / गाइड पिन चेक करो (Check locator & guide pins)",
        "standard": "पिन आउट, डेंट और स्लीपर नहीं (No wear, dent or slippage)",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "D",
        "frequency": "D",
        "action_clean": True,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "60 DPT",
        "sort_order": 10,
    },
    {
        "sub_no": "2.4",
        "assembly": "2. FIXTURE",
        "sub_assembly": "फिक्सचर",
        "check_point": "गाइड पिन, स्लाइडर लूब्रिकेशन चेक करो (Check guide pin & slider lubrication)",
        "standard": "ऑइलिंग करो ठीक से (Proper oil film present)",
        "tool_type": JHChecklistItem.ToolType.TOOL,
        "rank": "A",
        "frequency": "D",
        "action_clean": True,
        "action_lubricate": True,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "60 DPT",
        "sort_order": 11,
    },
    {
        "sub_no": "2.5",
        "assembly": "2. FIXTURE",
        "sub_assembly": "फिक्सचर",
        "check_point": "प्रॉक्सिमिटी सेंसर चेक करो (Check proximity sensor position)",
        "standard": "सेंसर आउट और लूज नहीं चाहिए (Sensor firm, correctly aligned)",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "D",
        "frequency": "D",
        "action_clean": True,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "60 DPT",
        "sort_order": 12,
    },
    {
        "sub_no": "2.6",
        "assembly": "2. FIXTURE",
        "sub_assembly": "फिक्सचर",
        "check_point": "एयर लीकेज चेक करो (Check pneumatic lines for air leaks)",
        "standard": "आवाज नहीं (No audible air hissing / leakage)",
        "tool_type": JHChecklistItem.ToolType.TOUCH,
        "rank": "A",
        "frequency": "D",
        "action_clean": False,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "60 DPT",
        "sort_order": 13,
    },
    {
        "sub_no": "2.7",
        "assembly": "2. FIXTURE",
        "sub_assembly": "फिक्सचर",
        "check_point": "क्लैंपिंग सिलेंडर के सभी बोल्ट्स चेक करो (Check clamping cylinder mounting bolts)",
        "standard": "ठीक से टाइट (Fully tightened, no loose bolts)",
        "tool_type": JHChecklistItem.ToolType.TOOL,
        "rank": "D",
        "frequency": "D",
        "action_clean": False,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": True,
        "timing_sec": "30 DPT",
        "sort_order": 14,
    },
    {
        "sub_no": "2.8",
        "assembly": "2. FIXTURE",
        "sub_assembly": "फिक्सचर",
        "check_point": "अर्थिंग प्लेट का बोल्ट्स चेक करो (Check earthing grounding plate bolts)",
        "standard": "ठीक से टाइट (Firm mechanical & electrical contact)",
        "tool_type": JHChecklistItem.ToolType.TOOL,
        "rank": "D",
        "frequency": "D",
        "action_clean": False,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": True,
        "timing_sec": "10 DPT",
        "sort_order": 15,
    },

    # 3. TEACH PENDANT
    {
        "sub_no": "3.1",
        "assembly": "3. TEACH PENDANT",
        "sub_assembly": "केबल",
        "check_point": "केबल प्रॉपर रूटिंग चेक करो (Check pendant cable routing & health)",
        "standard": "कटा / डैमेज नहीं (No cuts, twists, or wire damage)",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "A",
        "frequency": "D",
        "action_clean": False,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "5 DPT",
        "sort_order": 16,
    },
    {
        "sub_no": "3.2",
        "assembly": "3. TEACH PENDANT",
        "sub_assembly": "पेंडेंट",
        "check_point": "पेंडेंट बॉडी और स्क्रीन साफ करो (Clean pendant body & screen)",
        "standard": "धूल और तेल से मुक्त (Free from oil, dust & marks)",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "A",
        "frequency": "D",
        "action_clean": True,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "10 DPT",
        "sort_order": 17,
    },

    # 4. ROBOT
    {
        "sub_no": "4.1",
        "assembly": "4. ROBOT",
        "sub_assembly": "रोबोट",
        "check_point": "रोबोट आर्म सफाई (Clean robot mechanical arm & joints)",
        "standard": "धूल और तेल से मुक्त (Free from spatter & dirt)",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "B",
        "frequency": "D",
        "action_clean": True,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "15 DPT",
        "sort_order": 18,
    },
    {
        "sub_no": "4.2",
        "assembly": "4. ROBOT",
        "sub_assembly": "रोबोट",
        "check_point": "वायर फीडर रोलर टेंशन चेक करो (Check wire feeder roller tension)",
        "standard": "रोलर 1.2 mm है ठीक से मैच (Correct wire feeder tension)",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "A",
        "frequency": "D",
        "action_clean": False,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": True,
        "timing_sec": "30 DPT",
        "sort_order": 19,
    },
    {
        "sub_no": "4.3",
        "assembly": "4. ROBOT",
        "sub_assembly": "रोबोट",
        "check_point": "लाइनर स्पैटर और डस्ट चेक करो (Check welding wire liner)",
        "standard": "कोई स्पैटर नहीं बिल्कुल क्लीन (Smooth wire feed, clean)",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "D",
        "frequency": "D",
        "action_clean": False,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "30 DPT",
        "sort_order": 20,
    },
    {
        "sub_no": "4.4",
        "assembly": "4. ROBOT",
        "sub_assembly": "रोबोट",
        "check_point": "नोजल स्पैटर और डस्ट चेक करो (Check gas nozzle cleanliness)",
        "standard": "कोई स्पैटर नहीं बिल्कुल क्लीन (Spatter free gas flow)",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "D",
        "frequency": "D",
        "action_clean": True,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "30 DPT",
        "sort_order": 21,
    },
    {
        "sub_no": "4.5",
        "assembly": "4. ROBOT",
        "sub_assembly": "रोबोट",
        "check_point": "टॉर्च और नेक सफाई (Clean torch body and neck)",
        "standard": "धूल और स्पैटर से मुक्त (Free from spatter & foreign particles)",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "D",
        "frequency": "D",
        "action_clean": True,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "30 DPT",
        "sort_order": 22,
    },
    {
        "sub_no": "4.6",
        "assembly": "4. ROBOT",
        "sub_assembly": "रोबोट",
        "check_point": "कांटेक्ट टिप और टिप होल्डर चेक करो (Check contact tip & tip holder)",
        "standard": "कोई स्पैटर नहीं बिल्कुल क्लीन (Clean contact tip, secure fit)",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "D",
        "frequency": "D",
        "action_clean": True,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "30 DPT",
        "sort_order": 23,
    },
    {
        "sub_no": "4.7",
        "assembly": "4. ROBOT",
        "sub_assembly": "रोबोट",
        "check_point": "कटर सफाई (Clean wire cutter blade & mechanism)",
        "standard": "धूल और कोटिंग से मुक्त (Clean sharp cut, free from debris)",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "D",
        "frequency": "D",
        "action_clean": True,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "60 DPT",
        "sort_order": 24,
    },

    # 5. AUTO NOZZLE CLEANING
    {
        "sub_no": "5.1",
        "assembly": "5. AUTO NOZZLE CLEANING",
        "sub_assembly": "ऑयल टैंक",
        "check_point": "एंटी स्पैटर तेल है क्या चेक करो (Check anti-spatter reamer oil tank level)",
        "standard": "एंटी स्पैटर तेल पर्याप्त (Sufficient oil level)",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "D",
        "frequency": "D",
        "action_clean": False,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "15 DPT",
        "sort_order": 25,
    },
    {
        "sub_no": "5.2",
        "assembly": "5. AUTO NOZZLE CLEANING",
        "sub_assembly": "ऑटो नोजल क्लीनिंग यूनिट",
        "check_point": "ऑटो नोजल क्लीनिंग का बटन प्रेस करो और रोटेशन/स्प्रे चेक करो (Test auto nozzle reamer cycle & spray)",
        "standard": "प्रॉपर काम करना चाहिए (Reamer & spray cycle operational)",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "D",
        "frequency": "D",
        "action_clean": True,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "30 DPT",
        "sort_order": 26,
    },

    # 6. TTO / TORCH
    {
        "sub_no": "6.1",
        "assembly": "6. TTO / TORCH",
        "sub_assembly": "टॉर्च",
        "check_point": "टॉर्च पोजीशन चेक करो (Check torch tip alignment & angle)",
        "standard": "टॉर्च पर कोई स्पैटर और मॉडिफिकेशन नहीं (Standard zero position, free from spatter)",
        "tool_type": JHChecklistItem.ToolType.VISUAL,
        "rank": "D",
        "frequency": "D",
        "action_clean": True,
        "action_lubricate": False,
        "action_inspect": True,
        "action_retighten": False,
        "timing_sec": "8 DPT",
        "sort_order": 27,
    },
]


class Command(BaseCommand):
    help = 'Seeds standard 27 Jishu Hozen (Autonomous Maintenance) checklist items into PostgreSQL.'

    def handle(self, *args, **options):
        created_count = 0
        updated_count = 0

        for item_data in CHECKLIST_ITEMS:
            obj, created = JHChecklistItem.objects.update_or_create(
                sub_no=item_data["sub_no"],
                defaults=item_data
            )
            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(self.style.SUCCESS(
            f"Successfully seeded JH Checklist Items into PostgreSQL: {created_count} created, {updated_count} updated."
        ))
