# Generated by Django 6.0.7 on 2026-09-02 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0002_alter_calibrationequipment_calibration_frequency_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationequipment',
            name='acceptable_error',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='calibrationequipment',
            name='acceptance_criteria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='calibrationequipment',
            name='history_card_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='calibrationequipment',
            name='least_count',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='calibrationequipment',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='calibrationequipment',
            name='model_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='calibrationequipment',
            name='range_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField()),
                ('calibration_date', models.DateField()),
                ('result', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=10)),
                ('calibration_agency', models.CharField(blank=True, max_length=150)),
                ('report_number', models.CharField(blank=True, max_length=100)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('traceability_certificate_number', models.CharField(blank=True, max_length=100)),
                ('specified_size', models.CharField(blank=True, max_length=100)),
                ('calibration_details', models.TextField(blank=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibration_records', to='calibration.calibrationequipment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calibration_records',
                'ordering': ['-calibration_date', '-created_at'],
            },
        ),
    ]
