# Generated by Django 6.0.7 on 2026-09-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0003_calibrationequipment_acceptable_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrecord',
            name='report_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='calibrationrecord',
            name='report_file',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calibrationrecord',
            name='report_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='calibrationrecord',
            name='report_file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
