# Generated by Django 6.0.7 on 2026-09-02 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0004_calibrationrecord_report_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationPlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(db_index=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibration_plan_entries', to='calibration.calibrationequipment')),
            ],
            options={
                'db_table': 'calibration_plan_entries',
                'ordering': ['planned_date', 'equipment__equipment_id'],
            },
        ),
    ]
