# Generated by Django 6.0.7 on 2026-09-02 10:26

from django.db import migrations, models


def create_initial_plan_entries(apps, schema_editor):
    equipment_model = apps.get_model('calibration', 'CalibrationEquipment')
    plan_model = apps.get_model('calibration', 'CalibrationPlanEntry')
    plan_model.objects.bulk_create([
        plan_model(equipment=equipment, planned_date=equipment.next_calibration_date)
        for equipment in equipment_model.objects.all()
    ], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0005_calibrationplanentry'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='calibrationplanentry',
            constraint=models.UniqueConstraint(fields=('equipment', 'planned_date'), name='unique_equipment_calibration_plan_date'),
        ),
        migrations.RunPython(create_initial_plan_entries, migrations.RunPython.noop),
    ]
