# Generated by Django 5.1.5 on 2026-08-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_priority_from_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminder_sent',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('flagged_issue', 'Flagged Issue'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
