# Generated by Django 5.1.5 on 2026-09-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreport',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='bugreport',
            name='screenshot_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='screenshot_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
