# Generated by Django 6.0.7 on 2026-07-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=150)),
                ('parameter_code', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=20)),
                ('nominal_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('upper_tolerance', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lower_tolerance', models.DecimalField(decimal_places=4, max_digits=10)),
                ('upper_limit', models.DecimalField(decimal_places=4, editable=False, max_digits=12)),
                ('lower_limit', models.DecimalField(decimal_places=4, editable=False, max_digits=12)),
                ('measurement_type', models.CharField(choices=[('dimensional', 'Dimensional'), ('visual', 'Visual'), ('weight', 'Weight'), ('surface', 'Surface Finish')], default='dimensional', max_length=20)),
                ('is_critical', models.BooleanField(default=False)),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('voice_prompt', models.CharField(blank=True, help_text='e.g. "Please say the bore diameter measurement"', max_length=200)),
            ],
            options={
                'db_table': 'inspection_parameters',
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('first_piece', 'First Piece'), ('hourly', 'Hourly'), ('final', 'Final')], max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inspection_templates',
                'ordering': ['part', 'inspection_type', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50, unique=True)),
                ('part_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('drawing_number', models.CharField(blank=True, max_length=50)),
                ('revision', models.CharField(blank=True, default='A', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parts',
                'ordering': ['part_number'],
            },
        ),
    ]
