# Generated by Django 6.0.7 on 2026-08-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontemplate',
            name='target_parameter_count',
            field=models.PositiveIntegerField(default=10, help_text='Expected total parameter count configured by supervisor (e.g. 18, 10, 4)'),
        ),
        migrations.AlterField(
            model_name='inspectionparameter',
            name='parameter_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
