# Generated by Django 6.0.7 on 2026-08-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_inspectiontemplate_target_parameter_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontemplate',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Custom Operation Name e.g. Op 10 - Rough Turning', max_length=150),
        ),
    ]
