# Generated by Django 6.0.7 on 2026-08-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_inspectiontemplate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionparameter',
            name='control_method',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inspectionparameter',
            name='measurement_technique',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inspectionparameter',
            name='sample_size',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
