# Generated by Django 6.0.7 on 2026-08-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_inspectionparameter_control_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionparameter',
            name='measurement_type',
            field=models.CharField(choices=[('dimensional', 'Dimensional'), ('visual', 'Visual'), ('weight', 'Weight'), ('surface', 'Surface Finish'), ('min_limit', 'Min Limit'), ('max_limit', 'Max Limit')], default='dimensional', max_length=20),
        ),
    ]
