# Generated by Django 6.0.7 on 2026-08-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_alter_inspectionparameter_measurement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontemplate',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Dispatched and live for operators and inspectors on mobile'),
        ),
        migrations.AddField(
            model_name='inspectiontemplate',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
