# Generated by Django 6.0.7 on 2026-08-10 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_inspectiontemplate_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=150)),
                ('parameter_code', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('data_type', models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text'), ('yes_no', 'Yes / No'), ('selection', 'Selection')], default='numeric', max_length=20)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('specification', models.CharField(blank=True, default='', max_length=150)),
                ('nominal_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('upper_tolerance', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('lower_tolerance', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('lower_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_parameters', to='parts.inspectiontemplate')),
            ],
            options={
                'db_table': 'process_parameters',
                'ordering': ['sequence_order'],
            },
        ),
    ]
