# Generated by Django 6.0.7 on 2026-08-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_processparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='processparameter',
            name='measurement_type',
            field=models.CharField(blank=True, choices=[('dimensional', 'Dimensional'), ('visual', 'Visual'), ('weight', 'Weight'), ('surface', 'Surface Finish'), ('min_limit', 'Min Limit'), ('max_limit', 'Max Limit')], default='dimensional', help_text='Controls how upper/lower limits are computed for numeric parameters.', max_length=20),
        ),
    ]
