# Generated by Django 5.1.5 on 2026-09-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_processparameter_measurement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontemplate',
            name='cycle_time_mins',
            field=models.FloatField(default=0.0, help_text='Cycle time per operation in minutes'),
        ),
    ]
