# Generated by Django 6.0.7 on 2026-09-08 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_inspectiontemplate_cycle_time_mins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPlanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_plan_number', models.CharField(help_text='Unique Control Plan Number e.g. CP-101', max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('current_revision', models.CharField(default='v1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_control_plans', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(blank=True, help_text='Optional link to a Part', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_plans', to='parts.part')),
            ],
            options={
                'db_table': 'control_plan_documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlPlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_code', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='control_plans/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('change_notes', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('control_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='parts.controlplandocument')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_control_plan_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'control_plan_versions',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DrawingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_number', models.CharField(help_text='Unique Drawing Number e.g. DWG-101', max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('current_revision', models.CharField(default='Rev A', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drawings', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(blank=True, help_text='Optional link to a Part', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawings', to='parts.part')),
            ],
            options={
                'db_table': 'drawing_documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DrawingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_code', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='drawings/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('change_notes', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='parts.drawingdocument')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_drawing_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drawing_versions',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
