# Generated by Django 6.0.7 on 2026-09-22 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0011_controlplandocument_controlplanversion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontemplate',
            name='approval_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inspectiontemplate',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectiontemplate',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectiontemplate',
            name='assigned_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_template_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectiontemplate',
            name='assigned_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_template_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectiontemplate',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectiontemplate',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inspectiontemplate',
            name='review_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inspectiontemplate',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectiontemplate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectiontemplate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('reviewed', 'Reviewed / Awaiting Approval'), ('approved', 'Approved & Dispatched'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20),
        ),
    ]
