# Generated by Django 6.0.7 on 2026-09-22 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0012_inspectiontemplate_approval_comments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcr_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('form_doc_no', models.CharField(blank=True, default='DKI/MR/F/05', max_length=50)),
                ('change_type', models.CharField(choices=[('modification', 'Parameter Specification Modification'), ('addition', 'New Parameter Addition'), ('deletion', 'Parameter Deletion')], default='modification', max_length=20)),
                ('is_process_parameter', models.BooleanField(default=False)),
                ('parameter_code', models.CharField(max_length=100)),
                ('parameter_name', models.CharField(max_length=255)),
                ('current_specification', models.JSONField(blank=True, default=dict)),
                ('proposed_specification', models.JSONField(blank=True, default=dict)),
                ('basis_for_change', models.TextField(help_text='Engineering / quality rationale for change')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('awaiting_review', 'Awaiting Review'), ('reviewed', 'Reviewed & Recommended'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented')], db_index=True, default='awaiting_review', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_remarks', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('implemented_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_template_dcrs', to=settings.AUTH_USER_MODEL)),
                ('assigned_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_template_dcr_approvals', to=settings.AUTH_USER_MODEL)),
                ('assigned_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_template_dcr_reviews', to=settings.AUTH_USER_MODEL)),
                ('parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='parts.inspectionparameter')),
                ('process_parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='parts.processparameter')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raised_template_dcrs', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_template_dcrs', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_template_dcrs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='parts.inspectiontemplate')),
            ],
            options={
                'db_table': 'template_change_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
