# Generated by Django 6.0.7 on 2026-09-22 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0013_templatechangerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controlplandocument',
            name='approval_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='controlplandocument',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlplandocument',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_control_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlplandocument',
            name='assigned_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_control_plan_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlplandocument',
            name='assigned_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_control_plan_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlplandocument',
            name='phase',
            field=models.CharField(choices=[('prototype', 'Prototype'), ('pre_launch', 'Pre-Launch'), ('production', 'Production')], db_index=True, default='production', max_length=20),
        ),
        migrations.AddField(
            model_name='controlplandocument',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_control_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlplandocument',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='controlplandocument',
            name='review_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='controlplandocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlplandocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_control_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlplandocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('reviewed', 'Reviewed / Awaiting Approval'), ('approved', 'Approved & Released'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='controlplanversion',
            name='change_type',
            field=models.CharField(blank=True, default='initial', max_length=50),
        ),
        migrations.AddField(
            model_name='drawingdocument',
            name='approval_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='drawingdocument',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawingdocument',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_drawings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drawingdocument',
            name='assigned_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drawing_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drawingdocument',
            name='assigned_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drawing_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drawingdocument',
            name='doc_type',
            field=models.CharField(choices=[('customer', 'Customer Drawing'), ('internal', 'Internal Manufacturing Drawing'), ('tooling', 'Tooling & Fixture Drawing')], db_index=True, default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='drawingdocument',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_drawings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drawingdocument',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='drawingdocument',
            name='review_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='drawingdocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawingdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_drawings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drawingdocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('reviewed', 'Reviewed / Awaiting Approval'), ('approved', 'Approved & Released'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='drawingversion',
            name='change_type',
            field=models.CharField(blank=True, default='initial', max_length=50),
        ),
    ]
