# Generated by Django 5.1.5 on 2026-09-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_alter_machine_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='shift_duration_hours',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='plant',
            name='total_break_mins',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
