# Generated by Django 6.0.7 on 2026-09-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_factory_company_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='available_working_minutes',
            field=models.IntegerField(default=420),
        ),
        migrations.AddField(
            model_name='factory',
            name='lunch_break_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='factory',
            name='shift_hours',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='factory',
            name='tea_break_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='factory',
            name='total_shifts_per_day',
            field=models.IntegerField(default=3),
        ),
    ]
