# Generated by Django 5.1.5 on 2026-09-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_plant_shift_duration_hours_plant_total_break_mins'),
        ('machines', '0004_factory_available_working_minutes_and_more'),
    ]

    operations = [
    ]
