# Generated by Django 5.1.5 on 2026-09-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_merge_20260905_1146'),
        ('machines', '0005_merge_20260905_1215'),
    ]

    operations = [
    ]
