# Generated by Django 6.0.7 on 2026-09-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_merge_20260908_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='logo_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
