# Generated by Django 6.0.7 on 2026-09-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_merge_20260908_1305'),
        ('machines', '0006_merge_20260908_2318'),
    ]

    operations = [
    ]
