# Generated by Django 5.1.5 on 2026-09-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_factory_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
