# Generated by Django 6.0.7 on 2026-10-02 09:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_factory_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
