# Generated by Django 6.0.7 on 2026-10-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_alter_factory_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='shift_1_start',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='factory',
            name='shift_2_start',
            field=models.TimeField(default='16:00:00'),
        ),
        migrations.AddField(
            model_name='factory',
            name='shift_3_start',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
